### ISSUE TITLE
capture packets from array of interfaces

### ISSUE THREAD

**Issue by bobfly** [lemontree55/packetgen#119]
Is there a way to capture from multiple interfaces since `iface` param is string?
https://github.com/sdaubert/packetgen/blob/master/lib/packetgen/capture.rb#L30

**Comment by sdaubert** [comment]
Hi @bobfly, thank you for your interest about Packetgen.

There is no way to capture packets from multiple selected interfaces, as the underlying library (PcapRUB) does not handle it. Nevertheless, a string `any` passed as interface argument enables capturing on **all** interfaces on Linux since kernel 2.2.
